# Generated by Django 5.0 on 2023-12-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avtomobile',
            name='image',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='post.jpg', upload_to='')),
                ('avto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.avtomobile')),
            ],
        ),
    ]
