# Generated by Django 5.0 on 2023-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0002_remove_avtomobile_image_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
